import type {Metadata} from 'next'
import './globals.css'
import {Rubik} from 'next/font/google'
import {WeatherProvider} from '../context/WeatherProvider'
import Background from '../components/Background'
import Header from '../components/Header'

const rubik = Rubik({
	subsets: ['latin'],
	weight: ['300','400','500','600','700','800','900'],
	display: 'swap',
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body
	    className={`${rubik.className} bg-gradient-to-br from-[#7D7F8A] to-[#202538] min-h-screen h-fit relative`}
    >
      <WeatherProvider>
	      <Header />
        <Background />
        {children}
      </WeatherProvider>
      </body>
    </html>
  );
}
